INSERT INTO bulario_medications (id, nome, principio_ativo, categoria, classe, forma_farmaceutica, via, controlado, pediatria, gestacao_seguro, dose_adulto, dose_maxima, efeitos_adversos_comuns, efeitos_adversos_graves, mecanismo_acao, indicacoes, monitorizacao, nomes_comerciais, tags, tarja, observacoes, diluicao, tempo_infusao, dose_pediatrica, ajuste_renal) VALUES
-- NEFROLOGIA (20 items)
('nefro-losartana-50','Losartana 50mg','Losartana','Nefrologia','BRA','Comprimido','VO',false,false,false,'50-100 mg 1x/dia','100 mg/dia','Tontura, hipotensão, hipercalemia','Angioedema, IRA','Antagonista do receptor AT1 da angiotensina II','Nefropatia diabética, HAS com proteinúria, IC','Cr, K+, proteinúria','{"Cozaar","Losartec"}','{"nefrologia","HAS","nefropatia diabética","BRA"}','Vermelha','Nefroprotetor em diabetes tipo 2','','','','Não iniciar se TFG < 30 sem supervisão'),
('nefro-enalapril-nefro','Enalapril Nefroprotetor','Enalapril','Nefrologia','IECA','Comprimido','VO',false,false,false,'5-20 mg 2x/dia','40 mg/dia','Tosse seca, hipotensão, hipercalemia','Angioedema, IRA','Inibidor da ECA, reduz angiotensina II','Nefropatia com proteinúria, HAS, IC','Cr, K+, proteinúria','{"Renitec"}','{"nefrologia","IECA","proteinúria"}','Vermelha','Reduz proteinúria em 30-40%','','','','Ajustar dose se ClCr < 30'),
('nefro-dapagliflozina-drc','Dapagliflozina DRC','Dapagliflozina','Nefrologia','Inibidor de SGLT2','Comprimido','VO',false,false,false,'10 mg 1x/dia','10 mg/dia','ITU, candidíase genital, poliúria','Cetoacidose euglicêmica, fasceíte necrosante','Inibição do cotransportador SGLT2 no túbulo proximal renal','DRC (com ou sem diabetes), IC, redução de progressão renal','TFG, glicemia, cetonúria','{"Forxiga"}','{"nefrologia","SGLT2","DRC","cardiorrenal"}','Vermelha','Benefício nefroprotetor independente de diabetes (DAPA-CKD)','','','','Pode iniciar até TFG 20; descontinuar em diálise'),
('nefro-empagliflozina-drc','Empagliflozina DRC','Empagliflozina','Nefrologia','Inibidor de SGLT2','Comprimido','VO',false,false,false,'10 mg 1x/dia','10 mg/dia','Candidíase genital, ITU, hipotensão','Cetoacidose, desidratação','Inibição de SGLT2, reduz reabsorção de glicose e sódio','DRC, IC com FE reduzida','TFG, K+, glicemia','{"Jardiance"}','{"nefrologia","SGLT2","IC","DRC"}','Vermelha','EMPA-KIDNEY: redução de 28% em progressão renal','','','','Pode usar até TFG 20'),
('nefro-alopurinol-nefro','Alopurinol Nefrológico','Alopurinol','Nefrologia','Inibidor de xantina oxidase','Comprimido','VO',false,false,false,'100-300 mg/dia','800 mg/dia','Rash, náusea, diarreia','Síndrome de hipersensibilidade ao alopurinol (DRESS/SJS)','Inibidor de xantina oxidase, reduz produção de ácido úrico','Hiperuricemia com gota e DRC, nefrolitíase por ácido úrico','Ácido úrico, função renal','{"Zyloric"}','{"nefrologia","gota","hiperuricemia"}','Vermelha','Iniciar 100 mg/dia e titular. Testar HLA-B*5801 em populações de risco','','','','100 mg/dia se ClCr < 30'),
('nefro-sevelamer','Sevelâmer','Sevelâmer','Nefrologia','Quelante de fósforo','Comprimido','VO',false,false,false,'800 mg 3x/dia com refeições (titular conforme fósforo)','','Náusea, constipação, dor abdominal','Obstrução intestinal (rara)','Polímero catiônico, quelação de fosfato no TGI','Hiperfosfatemia em DRC estágios 4-5 e diálise','Fósforo sérico a cada 2-4 semanas','{"Renagel","Renvela"}','{"nefrologia","diálise","hiperfosfatemia"}','Vermelha','Não absorvido sistemicamente','','','',''),
('nefro-calcitriol','Calcitriol','Calcitriol','Nefrologia','Vitamina D ativa','Cápsula','VO',false,false,false,'0,25-1 mcg/dia','','Hipercalcemia, hiperfosfatemia','Calcinose, nefrocalcinose','Forma ativa de vitamina D3 (1,25-dihidroxivitamina D)','Hiperparatireoidismo secundário em DRC, hipocalcemia','Cálcio, fósforo, PTH a cada 1-3 meses','{"Rocaltrol"}','{"nefrologia","PTH","vitamina D","DRC"}','Vermelha','','','','',''),
('nefro-cinacalcete','Cinacalcete','Cinacalcete','Nefrologia','Calcimimético','Comprimido','VO',false,false,false,'30 mg 1x/dia (titular até 180 mg/dia)','180 mg/dia','Náusea, vômitos, hipocalcemia','Hipocalcemia grave, prolongamento QT','Ativação do receptor sensor de cálcio na paratireoide','Hiperparatireoidismo secundário em diálise, HPT primário inoperável','PTH, Ca, P a cada 1-4 semanas','{"Mimpara"}','{"nefrologia","hiperparatireoidismo","calcimimético"}','Vermelha','','','','',''),
('nefro-eritropoietina-drc','Eritropoietina (DRC)','Eritropoietina alfa','Nefrologia','Estimulante de eritropoiese','Ampola','SC',false,false,false,'50-100 UI/kg 3x/semana SC (ou 10.000 UI 1x/semana)','','Hipertensão, cefaleia, dor no local','AVC, TEV, aplasia pura de células vermelhas','Estimula diferenciação e maturação de eritrócitos','Anemia da DRC (Hb < 10 g/dL)','Hb mensal (alvo 10-12 g/dL), ferro sérico, ferritina','{"Eprex","Eritromax"}','{"nefrologia","anemia","DRC","eritropoietina"}','Vermelha','Não ultrapassar Hb 12 g/dL (risco cardiovascular)','','','',''),
('nefro-darbepoetina','Darbepoetina alfa','Darbepoetina alfa','Nefrologia','Estimulante de eritropoiese','Ampola','SC',false,false,false,'0,45 mcg/kg 1x/semana ou 0,75 mcg/kg a cada 2 semanas','','Hipertensão, cefaleia','AVC, TEV','Análogo de eritropoietina com meia-vida mais longa','Anemia da DRC','Hb mensal (alvo 10-12 g/dL), ferro','{"Aranesp"}','{"nefrologia","anemia","DRC","darbepoetina"}','Vermelha','','','','',''),
('nefro-ferro-sacarato-nefro','Ferro Sacarato (Nefrologia)','Hidróxido de ferro III sacarato','Nefrologia','Ferro parenteral','Ampola','IV',false,false,false,'100-200 mg IV por sessão; dose total até 1000 mg','200 mg/sessão','Hipotensão, náusea, cefaleia','Anafilaxia (rara)','Reposição de ferro para eritropoiese','Deficiência de ferro em DRC e diálise (ferritina < 500, IST < 30%)','Ferritina, IST antes de cada ciclo','{"Noripurum IV"}','{"nefrologia","ferro","diálise","anemia"}','Vermelha','','Diluir 100 mg em 100 mL SF','15-30 minutos','',''),
('nefro-bicarbonato-sodio-oral','Bicarbonato de Sódio Oral','Bicarbonato de sódio','Nefrologia','Alcalinizante','Comprimido','VO',false,false,false,'500-2000 mg 2-3x/dia (titular para HCO3 > 22)','','Distensão abdominal, eructação','Alcalose metabólica, sobrecarga de sódio','Tamponamento de H+, correção de acidose metabólica','Acidose metabólica na DRC (HCO3 < 22)','Gasometria venosa, Na+','{"Bicarbonato de Sódio"}','{"nefrologia","acidose","DRC"}','Sem tarja','Pode retardar progressão da DRC','','','',''),
('nefro-poliestireno-sulfonato','Poliestirenossulfonato de Cálcio','Poliestirenossulfonato de cálcio','Nefrologia','Quelante de potássio','Pó para suspensão','VO',false,false,false,'15-30 g 1-4x/dia VO ou retal','','Constipação, náusea, hipocalemia','Necrose intestinal (especialmente com sorbitol)','Resina de troca iônica, troca K+ por Ca2+ no intestino','Hipercalemia em DRC, hipercalemia aguda (adjuvante)','K+ sérico a cada 4-6h na aguda','{"Sorcal"}','{"nefrologia","hipercalemia","resina"}','Vermelha','Evitar associação com sorbitol (risco de necrose intestinal)','','','',''),
('nefro-patiromer','Patiromer','Patiromer','Nefrologia','Quelante de potássio','Pó para suspensão','VO',false,false,false,'8,4 g 1x/dia, titular até 25,2 g','25,2 g/dia','Constipação, hipomagnesemia, dor abdominal','Hipocalemia','Polímero de troca catiônica, liga K+ no cólon','Hipercalemia crônica em DRC, pacientes em uso de IECA/BRA','K+ e Mg2+ séricos','{"Veltassa"}','{"nefrologia","hipercalemia","quelante"}','Vermelha','Separar 3h de outros medicamentos orais','','','',''),
('nefro-ciclofosfamida-nefro','Ciclofosfamida (Nefrite Lúpica)','Ciclofosfamida','Nefrologia','Imunossupressor','Ampola','IV',false,false,false,'500 mg-1 g/m² IV mensal por 6 meses (NIH) ou 500 mg IV quinzenal (Euro-Lupus)','','Náusea, alopecia, leucopenia','Cistite hemorrágica, infertilidade, neoplasias secundárias','Alquilante, crosslinking de DNA, imunossupressão','Nefrite lúpica classe III/IV, vasculites renais ANCA','Hemograma semanal, EAS, BHCG','{"Genuxal"}','{"nefrologia","lúpus","imunossupressor"}','Vermelha','Hidratação vigorosa + MESNA para proteção vesical','Diluir em 250-500 mL SF','30-60 minutos','',''),
('nefro-micofenolato-nefro','Micofenolato Mofetila (Nefrite)','Micofenolato mofetila','Nefrologia','Imunossupressor','Comprimido','VO',false,false,false,'1-1,5 g 2x/dia','3 g/dia','Diarreia, náusea, leucopenia','Infecções oportunistas, leucopenia grave','Inibidor de IMPDH, bloqueia síntese de purinas em linfócitos','Nefrite lúpica (manutenção), glomerulonefrites','Hemograma mensal, função hepática','{"CellCept","Myfortic"}','{"nefrologia","lúpus","imunossupressor"}','Vermelha','Alternativa à ciclofosfamida para manutenção','','','',''),
('nefro-tacrolimus-nefro','Tacrolimus (Transplante Renal)','Tacrolimus','Nefrologia','Imunossupressor','Cápsula','VO',false,false,false,'0,1-0,2 mg/kg/dia dividido em 2 doses','','Tremor, nefrotoxicidade, hiperglicemia, hipertensão','Nefrotoxicidade crônica, diabetes, linfoma','Inibidor de calcineurina, bloqueia ativação de linfócitos T','Imunossupressão em transplante renal','Nível sérico (alvo 5-15 ng/mL), Cr, glicemia, K+','{"Prograf","Envarsus"}','{"nefrologia","transplante","calcineurina"}','Vermelha','Nível terapêutico estreito — monitorização obrigatória','','','',''),
('nefro-everolimus','Everolimus','Everolimus','Nefrologia','Inibidor de mTOR','Comprimido','VO',false,false,false,'0,75 mg 2x/dia (ajustar por nível sérico)','','Estomatite, dislipidemia, proteinúria','Pneumonite, infecções oportunistas','Inibidor de mTOR, suprime proliferação de linfócitos T','Imunossupressão em transplante renal, neoplasias','Nível sérico (alvo 3-8 ng/mL), perfil lipídico, proteinúria','{"Certican","Afinitor"}','{"nefrologia","transplante","mTOR"}','Vermelha','','','','',''),
('nefro-prednisolona-nefro','Prednisolona (Síndrome Nefrótica)','Prednisolona','Nefrologia','Corticosteroide','Comprimido','VO',false,true,false,'60 mg/m²/dia ou 2 mg/kg/dia por 4-6 semanas, depois desmame','60 mg/dia','Cushing, hiperglicemia, insônia','Necrose avascular, osteoporose, infecções','Anti-inflamatório e imunossupressor via receptor glicocorticoide','Síndrome nefrótica idiopática, lesões mínimas, GESF','Glicemia, PA, K+, proteinúria','{"Prelone","Predsim"}','{"nefrologia","síndrome nefrótica","corticoide"}','Vermelha','','','','2 mg/kg/dia (máx 60 mg) crianças',''),
('nefro-rituximabe-nefro','Rituximabe (Nefrologia)','Rituximabe','Nefrologia','Anticorpo monoclonal','Ampola','IV',false,false,false,'375 mg/m² semanal x4 ou 1 g em D1 e D15','','Reação infusional, leucopenia','Leucoencefalopatia multifocal progressiva, reativação HBV','Anti-CD20, depleção de linfócitos B','Nefrite lúpica refratária, nefropatia membranosa, vasculite ANCA','Hemograma, imunoglobulinas, sorologias virais','{"MabThera","Ruxience"}','{"nefrologia","anticorpo","linfócito B"}','Vermelha','Pré-medicação: paracetamol + anti-histamínico + corticoide','Diluir em 250-500 mL SF','Primeira: 50 mg/h (aumentar progressivamente)','','')
ON CONFLICT (id) DO UPDATE SET nome=EXCLUDED.nome, principio_ativo=EXCLUDED.principio_ativo, categoria=EXCLUDED.categoria, classe=EXCLUDED.classe, mecanismo_acao=EXCLUDED.mecanismo_acao, indicacoes=EXCLUDED.indicacoes, tarja=EXCLUDED.tarja, nomes_comerciais=EXCLUDED.nomes_comerciais, tags=EXCLUDED.tags;