INSERT INTO bulario_medications (id, nome, principio_ativo, categoria, classe, forma_farmaceutica, via, controlado, pediatria, gestacao_seguro, dose_pediatrica, dose_maxima, efeitos_adversos_comuns, efeitos_adversos_graves, mecanismo_acao, indicacoes, monitorizacao, nomes_comerciais, tags, tarja, dose_adulto, diluicao, tempo_infusao, observacoes) VALUES
-- OTORRINOLARINGOLOGIA (14 items)
('orl-amoxicilina-clavulanato-susp','Amoxicilina-Clavulanato Suspensão','Amoxicilina + Ácido clavulânico','Otorrinolaringologia','Antibiótico','Suspensão oral','VO',false,true,false,'45-90 mg/kg/dia dividido em 2 doses','3 g/dia','Diarreia, rash, candidíase','Hepatite colestática, Stevens-Johnson','Aminopenicilina + inibidor de beta-lactamase','OMA recorrente, sinusite aguda bacteriana, amigdalite','','{"Clavulin"}','{"ORL","antibiótico","sinusite","otite"}','Vermelha','','','',''),
('orl-fluticasona-nasal','Fluticasona Nasal','Propionato de fluticasona','Otorrinolaringologia','Corticosteroide','Spray nasal','Nasal',false,true,false,'1 jato/narina 1x/dia (> 4 anos)','','Epistaxe, secura nasal, cefaleia','Perfuração de septo (rara)','Corticosteroide tópico, anti-inflamatório na mucosa nasal','Rinite alérgica, polipose nasal, rinossinusite crônica','','{"Flixonase","Avamys"}','{"ORL","rinite","corticoide nasal"}','Vermelha','2 jatos/narina 1x/dia','','',''),
('orl-mometasona-nasal','Mometasona Nasal','Furoato de mometasona','Otorrinolaringologia','Corticosteroide','Spray nasal','Nasal',false,true,false,'1 jato/narina 1x/dia (> 3 anos)','','Epistaxe, irritação nasal','','Corticosteroide tópico nasal de alta potência','Rinite alérgica, polipose nasal','','{"Nasonex"}','{"ORL","rinite","corticoide"}','Vermelha','2 jatos/narina 1x/dia','','',''),
('orl-budesonida-nasal','Budesonida Nasal','Budesonida','Otorrinolaringologia','Corticosteroide','Spray nasal','Nasal',false,true,false,'','','Epistaxe, secura nasal','','Corticosteroide tópico com alta afinidade por receptor glicocorticoide','Rinite alérgica e não alérgica, polipose nasal','','{"Busonid","Noex"}','{"ORL","rinite","corticoide"}','Vermelha','2 jatos/narina 2x/dia','','',''),
('orl-azelastina-nasal','Azelastina Nasal','Azelastina','Otorrinolaringologia','Anti-histamínico','Spray nasal','Nasal',false,false,false,'','','Gosto amargo, sonolência, epistaxe','','Anti-histamínico H1 tópico nasal de ação rápida','Rinite alérgica, rinite vasomotora','','{"Rino-Lastin"}','{"ORL","rinite","anti-histamínico"}','Vermelha','1-2 jatos/narina 2x/dia','','',''),
('orl-oximetazolina','Oximetazolina Nasal','Oximetazolina','Otorrinolaringologia','Descongestionante','Spray nasal','Nasal',false,false,false,'','','Secura nasal, ardência','Rinite medicamentosa (uso > 5 dias)','Agonista alfa-adrenérgico, vasoconstrição na mucosa nasal','Congestão nasal aguda (uso máximo 3-5 dias)','','{"Afrin","Nasivin"}','{"ORL","descongestionante","uso curto"}','Sem tarja','2-3 gotas/jatos por narina 2x/dia, máx 5 dias','','','Uso prolongado causa efeito rebote e rinite medicamentosa'),
('orl-ciprofloxacino-otologico','Ciprofloxacino Otológico','Ciprofloxacino + Dexametasona','Otorrinolaringologia','Antibiótico','Solução otológica','Otológica',false,false,false,'','','Prurido local, desconforto','','Quinolona tópica + corticosteroide anti-inflamatório','Otite externa, otite média com perfuração e tubo','','{"Ciprodex","Otociriax"}','{"ORL","otite","antibiótico tópico"}','Vermelha','4 gotas no ouvido afetado 2x/dia por 7 dias','','',''),
('orl-clotrimazol-otologico','Clotrimazol Otológico','Clotrimazol','Otorrinolaringologia','Antifúngico','Solução otológica','Otológica',false,false,false,'','','Irritação local','','Imidazol, inibição de síntese de ergosterol na membrana fúngica','Otomicose (otite externa fúngica)','','{"Canesten Otológico"}','{"ORL","otomicose","antifúngico"}','Vermelha','3-4 gotas 3x/dia por 14 dias','','',''),
('orl-clorexidina-spray','Clorexidina Spray Orofaríngeo','Digluconato de clorexidina','Otorrinolaringologia','Antisséptico','Solução oral','VO',false,false,false,'','','Manchamento dental, alteração do paladar','','Antisséptico catiônico, disrupta membrana celular bacteriana','Gengivite, estomatite, pós-operatório orofaríngeo','','{"Periogard"}','{"ORL","antisséptico","estomatite"}','Sem tarja','Bochechos 15 mL por 30 seg, 2x/dia','','',''),
('orl-benzidamina','Benzidamina Spray Oral','Benzidamina','Otorrinolaringologia','Anti-inflamatório','Spray oral','VO',false,false,false,'','','Dormência oral, ardência','','AINE tópico com ação anestésica local e anti-inflamatória','Faringite, amigdalite, mucosite oral, pós-operatório','','{"Flogoral","Ciflogex"}','{"ORL","faringite","tópico"}','Sem tarja','4-8 jatos a cada 1,5-3h','','',''),
('orl-carbocisteina','Carbocisteína','Carbocisteína','Otorrinolaringologia','Mucolítico','Xarope','VO',false,true,false,'10 mg/kg/dose 2-3x/dia','','Náusea, diarreia','','Mucolítico, normaliza secreção de muco alterando glicosilação de mucinas','Sinusite, bronquite, DPOC, otite secretora','','{"Mucoflux","Mucovit"}','{"ORL","mucolítico","sinusite"}','Sem tarja','750 mg 3x/dia','','',''),
('orl-loratadina','Loratadina','Loratadina','Otorrinolaringologia','Anti-histamínico','Comprimido','VO',false,true,false,'5 mg/dia (2-6 anos); 10 mg/dia (> 6 anos)','10 mg/dia','Cefaleia, sonolência leve','','Anti-histamínico H1 de 2ª geração, não sedativo','Rinite alérgica, urticária crônica, conjuntivite alérgica','','{"Claritin","Loralerg"}','{"ORL","alergia","anti-histamínico"}','Sem tarja','10 mg 1x/dia','','',''),
('orl-desloratadina','Desloratadina','Desloratadina','Otorrinolaringologia','Anti-histamínico','Comprimido','VO',false,true,false,'1,25 mg/dia (1-5 anos); 2,5 mg (6-11 anos)','','Cefaleia, fadiga, boca seca','','Metabólito ativo da loratadina, anti-histamínico H1 de 3ª geração','Rinite alérgica, urticária crônica','','{"Desalex","Esalerg"}','{"ORL","alergia","anti-histamínico"}','Vermelha','5 mg 1x/dia','','',''),
('orl-fexofenadina','Fexofenadina','Fexofenadina','Otorrinolaringologia','Anti-histamínico','Comprimido','VO',false,false,false,'','180 mg/dia','Cefaleia, náusea','','Anti-histamínico H1 de 2ª geração, não sedativo','Rinite alérgica sazonal, urticária crônica','','{"Allegra"}','{"ORL","alergia"}','Sem tarja','120-180 mg 1x/dia','','',''),
('orl-montelucaste','Montelucaste','Montelucaste sódico','Otorrinolaringologia','Antileucotrieno','Comprimido mastigável','VO',false,true,false,'4 mg (2-5 anos); 5 mg (6-14 anos)','','Cefaleia, dor abdominal','Alterações neuropsiquiátricas (raro: ideação suicida, pesadelos — FDA box warning)','Antagonista de receptor de leucotrieno CysLT1','Rinite alérgica, asma, polipose nasal (adjuvante)','','{"Singulair","Montelair"}','{"ORL","asma","antileucotrieno"}','Vermelha','10 mg à noite','','','')
ON CONFLICT (id) DO UPDATE SET nome=EXCLUDED.nome, principio_ativo=EXCLUDED.principio_ativo, categoria=EXCLUDED.categoria, classe=EXCLUDED.classe, mecanismo_acao=EXCLUDED.mecanismo_acao, indicacoes=EXCLUDED.indicacoes, tarja=EXCLUDED.tarja, nomes_comerciais=EXCLUDED.nomes_comerciais, tags=EXCLUDED.tags;