INSERT INTO bulario_medications (id, nome, principio_ativo, categoria, classe, forma_farmaceutica, via, controlado, pediatria, gestacao_seguro, dose_pediatrica, dose_maxima, efeitos_adversos_comuns, efeitos_adversos_graves, mecanismo_acao, indicacoes, monitorizacao, nomes_comerciais, tags, tarja, receita_tipo, observacoes, diluicao, tempo_infusao, dose_adulto) VALUES
-- PEDIATRIA (15 items)
('ped-paracetamol-gotas','Paracetamol Gotas Pediátrico','Paracetamol','Pediatria','Analgésico','Solução oral','VO',false,true,true,'10-15 mg/kg/dose a cada 4-6h','75 mg/kg/dia','Raros em doses terapêuticas','Hepatotoxicidade em superdose','Inibição central de COX, ação no centro termorregulador hipotalâmico','Febre e dor leve a moderada em lactentes e crianças','Função hepática se uso prolongado','{"Tylenol Bebê","Dôrico"}','{"pediatria","febre","analgesia"}','Sem tarja','','','','',''),
('ped-ibuprofeno-gotas','Ibuprofeno Gotas Pediátrico','Ibuprofeno','Pediatria','AINE','Suspensão oral','VO',false,true,false,'5-10 mg/kg/dose a cada 6-8h','40 mg/kg/dia','Dor abdominal, náusea','Sangramento GI, nefrotoxicidade','Inibição não seletiva de COX-1 e COX-2','Febre, dor e inflamação em crianças > 6 meses','','{"Alivium","Dalsy"}','{"pediatria","febre","anti-inflamatório"}','Sem tarja','','','','',''),
('ped-amoxicilina-susp','Amoxicilina Suspensão Pediátrica','Amoxicilina','Pediatria','Antibiótico','Suspensão oral','VO',false,true,true,'40-90 mg/kg/dia dividido em 2-3 doses','3 g/dia','Diarreia, rash, náusea','Anafilaxia, Stevens-Johnson','Inibição da síntese de parede celular bacteriana','OMA, sinusite, faringoamigdalite, pneumonia comunitária','','{"Amoxil","Novocilin"}','{"pediatria","antibiótico","otite"}','Vermelha','Simples','','','',''),
('ped-azitromicina-susp','Azitromicina Suspensão','Azitromicina','Pediatria','Antibiótico','Suspensão oral','VO',false,true,false,'10 mg/kg/dia no D1, depois 5 mg/kg/dia D2-D5','500 mg/dia','Diarreia, dor abdominal, náusea','Prolongamento QT, hepatotoxicidade','Ligação à subunidade 50S ribossômica, inibindo síntese proteica','OMA, faringite, pneumonia atípica, coqueluche','','{"Zitromax","Astro"}','{"pediatria","macrolídeo"}','Vermelha','','','','',''),
('ped-prednisolona-susp','Prednisolona Solução Oral','Prednisolona','Pediatria','Corticosteroide','Solução oral','VO',false,true,false,'1-2 mg/kg/dia por 3-5 dias','60 mg/dia','Aumento apetite, irritabilidade, insônia','Supressão adrenal, hiperglicemia, osteoporose','Anti-inflamatório e imunossupressor via receptores glicocorticoides','Crupe, asma aguda, síndrome nefrótica, artrite','','{"Prelone","Predsim"}','{"pediatria","corticoide","crupe","asma"}','Vermelha','','','','',''),
('ped-salbutamol-inal','Salbutamol Inalatório Pediátrico','Salbutamol','Pediatria','Broncodilatador','Aerossol','Inalatório',false,true,false,'2-4 jatos com espaçador a cada 20 min na crise','12 jatos/dia','Taquicardia, tremor, agitação','Hipocalemia, arritmia','Agonista beta-2 adrenérgico seletivo, relaxamento musculatura brônquica','Broncoespasmo, asma aguda, sibilância','','{"Aerolin"}','{"pediatria","asma","broncodilatador"}','Vermelha','','','','',''),
('ped-ondansetrona-susp','Ondansetrona Solução Oral','Ondansetrona','Pediatria','Antiemético','Solução oral','VO',false,true,false,'0,15 mg/kg/dose até 3x/dia','16 mg/dia','Cefaleia, constipação','Prolongamento QT','Antagonista seletivo do receptor 5-HT3','Náusea e vômitos em gastroenterite, pós-operatório','','{"Vonau Flash","Zofran"}','{"pediatria","antiemético"}','Vermelha','','','','',''),
('ped-dipirona-gotas','Dipirona Gotas Pediátrica','Dipirona sódica','Pediatria','Analgésico','Solução oral','VO',false,true,false,'10-25 mg/kg/dose a cada 6h','4 g/dia','Hipotensão leve','Agranulocitose, anafilaxia','Inibição de COX central e periférica','Febre e dor em crianças > 3 meses','','{"Novalgina Gotas"}','{"pediatria","febre","analgesia"}','Sem tarja','','','','',''),
('ped-sro','Sais de Reidratação Oral (SRO)','NaCl + KCl + Citrato de sódio + Glicose','Pediatria','Reidratante','Pó para solução oral','VO',false,true,true,'50-100 mL/kg em 4h (desidratação leve-moderada)','','Náusea, vômitos se administrado rápido','','Reposição hidroeletrolítica via cotransporte Na-glicose intestinal','Desidratação leve a moderada por diarreia aguda','','{"SRO OMS","Pedialyte"}','{"pediatria","diarreia","reidratação"}','Sem tarja','','','','',''),
('ped-nistatina-oral','Nistatina Suspensão Oral','Nistatina','Pediatria','Antifúngico','Suspensão oral','VO',false,true,false,'100.000 UI 4x/dia por 7-14 dias','','Náusea, diarreia','','Ligação ao ergosterol da membrana fúngica causando lise celular','Candidíase oral (sapinho) em lactentes e crianças','','{"Micostatin"}','{"pediatria","antifúngico","candidíase"}','Vermelha','','','','',''),
('ped-sulfato-ferroso-gotas','Sulfato Ferroso Gotas','Sulfato ferroso','Pediatria','Suplemento','Solução oral','VO',false,true,false,'3-6 mg Fe elementar/kg/dia (tratamento); 1 mg/kg/dia (profilaxia)','300 mg Fe elementar/dia','Dor abdominal, constipação, fezes escuras','Intoxicação por ferro em superdose','Reposição de ferro elementar para eritropoiese','Anemia ferropriva, profilaxia de anemia em lactentes','','{"Fer-In-Sol","Noripurum Gotas"}','{"pediatria","anemia","ferro"}','Sem tarja','','','','',''),
('ped-vitamina-d-gotas','Vitamina D Gotas','Colecalciferol','Pediatria','Suplemento','Solução oral','VO',false,true,true,'400-1000 UI/dia (profilaxia); 2000-6000 UI/dia (tratamento)','','Raros em doses adequadas','Hipercalcemia em superdose','Regulação do metabolismo de cálcio e fósforo','Profilaxia e tratamento de deficiência de vitamina D, raquitismo','','{"Addera D3","DePura Kids"}','{"pediatria","vitamina","suplemento"}','Sem tarja','','','','',''),
('ped-domperidona-gotas','Domperidona Gotas','Domperidona','Pediatria','Procinético','Suspensão oral','VO',false,true,false,'0,25 mg/kg/dose 3x/dia antes das refeições','30 mg/dia','Boca seca, cefaleia','Prolongamento QT, galactorreia','Antagonista dopaminérgico D2 periférico, aumenta motilidade gástrica','Refluxo gastroesofágico, náusea e vômitos','','{"Motilium"}','{"pediatria","refluxo","procinético"}','Vermelha','','','','',''),
('ped-cefalexina-susp','Cefalexina Suspensão','Cefalexina','Pediatria','Antibiótico','Suspensão oral','VO',false,true,false,'25-50 mg/kg/dia dividido em 3-4 doses','4 g/dia','Diarreia, náusea, rash','Anafilaxia, colite pseudomembranosa','Cefalosporina de 1ª geração, inibição de síntese de parede celular','Infecções de pele, ITU, faringite','','{"Keflex"}','{"pediatria","cefalosporina","pele"}','Vermelha','','','','',''),
('ped-dexametasona-gotas','Dexametasona Elixir','Dexametasona','Pediatria','Corticosteroide','Elixir','VO',false,true,false,'0,15-0,6 mg/kg dose única (crupe)','16 mg/dia','Hiperglicemia, irritabilidade','Supressão adrenal','Glicocorticoide potente, anti-inflamatório e imunossupressor','Crupe moderado-grave, edema de via aérea, pós-extubação','','{"Decadron Elixir"}','{"pediatria","crupe","corticoide"}','Vermelha','','','','','')
ON CONFLICT (id) DO UPDATE SET nome=EXCLUDED.nome, principio_ativo=EXCLUDED.principio_ativo, categoria=EXCLUDED.categoria, classe=EXCLUDED.classe, forma_farmaceutica=EXCLUDED.forma_farmaceutica, via=EXCLUDED.via, controlado=EXCLUDED.controlado, pediatria=EXCLUDED.pediatria, gestacao_seguro=EXCLUDED.gestacao_seguro, dose_pediatrica=EXCLUDED.dose_pediatrica, dose_maxima=EXCLUDED.dose_maxima, efeitos_adversos_comuns=EXCLUDED.efeitos_adversos_comuns, efeitos_adversos_graves=EXCLUDED.efeitos_adversos_graves, mecanismo_acao=EXCLUDED.mecanismo_acao, indicacoes=EXCLUDED.indicacoes, monitorizacao=EXCLUDED.monitorizacao, nomes_comerciais=EXCLUDED.nomes_comerciais, tags=EXCLUDED.tags, tarja=EXCLUDED.tarja;