INSERT INTO bulario_medications (id, nome, principio_ativo, categoria, classe, forma_farmaceutica, via, controlado, pediatria, gestacao_seguro, dose_adulto, dose_maxima, efeitos_adversos_comuns, efeitos_adversos_graves, mecanismo_acao, indicacoes, monitorizacao, nomes_comerciais, tags, tarja, observacoes) VALUES
-- GINECOLOGIA (20 items)
('gin-etinilestradiol-gestodeno','Etinilestradiol + Gestodeno','Etinilestradiol + Gestodeno','Ginecologia','Contraceptivo','Comprimido','VO',false,false,false,'1 comp/dia por 21 dias, pausa 7 dias','','Náusea, cefaleia, mastalgia, spotting','TEV, TEA, AVC','Inibição do eixo hipotálamo-hipófise-gonadal; suprime ovulação','Contracepção hormonal combinada','PA anual, perfil lipídico','{"Gynera","Femiane"}','{"ginecologia","contraceptivo","combinado"}','Vermelha','Contraindicado em tabagistas > 35 anos e histórico de TEV'),
('gin-levonorgestrel-emergencia','Levonorgestrel Emergência','Levonorgestrel','Ginecologia','Contraceptivo de emergência','Comprimido','VO',false,false,false,'1,5 mg dose única até 72h após relação','1,5 mg','Náusea, cefaleia, sangramento irregular','','Inibe ou retarda ovulação, altera muco cervical','Contracepção de emergência (pílula do dia seguinte)','','{"Postinor","Pozato"}','{"ginecologia","emergência","contraceptivo"}','Sem tarja','Eficácia diminui com o tempo: 95% até 24h, 85% 24-48h, 58% 48-72h'),
('gin-drospirenona-etinilestradiol','Drospirenona + Etinilestradiol','Drospirenona + Etinilestradiol','Ginecologia','Contraceptivo','Comprimido','VO',false,false,false,'1 comp/dia por 21 dias, pausa 7 dias','','Cefaleia, mastalgia, spotting','TEV, hipercalemia','Progestágeno com ação antimineralocorticoide e antiandrogênica','Contracepção, acne, SOP, TPM','K+ (ação antimineralocorticoide)','{"Yasmin","Yaz"}','{"ginecologia","contraceptivo","SOP","acne"}','Vermelha',''),
('gin-desogestrel','Desogestrel (Minipílula)','Desogestrel','Ginecologia','Contraceptivo','Comprimido','VO',false,false,false,'75 mcg 1x/dia uso contínuo sem pausa','','Sangramento irregular, amenorreia, cefaleia','','Progestágeno puro, inibe ovulação em 97% dos ciclos','Contracepção em lactantes, contraindicação a estrogênio','','{"Cerazette","Nactali"}','{"ginecologia","contraceptivo","progestágeno","amamentação"}','Vermelha','Pode ser usado durante amamentação'),
('gin-medroxiprogesterona-im','Medroxiprogesterona IM','Medroxiprogesterona','Ginecologia','Contraceptivo','Suspensão injetável','IM',false,false,false,'150 mg IM a cada 3 meses','','Ganho de peso, irregularidade menstrual, amenorreia','Perda de massa óssea (uso prolongado)','Progestágeno depot, inibe ovulação e altera endométrio','Contracepção de longa duração, endometriose','DMO se uso > 2 anos','{"Depo-Provera"}','{"ginecologia","contraceptivo","injetável"}','Vermelha',''),
('gin-diu-cobre','DIU de Cobre','Cobre','Ginecologia','Contraceptivo','Dispositivo intrauterino','Intrauterino',false,false,true,'Inserção por profissional; duração 5-10 anos','','Cólica, sangramento menstrual aumentado','Perfuração uterina (rara), expulsão','Ação espermicida do cobre, reação inflamatória endometrial','Contracepção de longa duração, contracepção de emergência até 5 dias','US controle pós-inserção','{"TCu380A","Multiload"}','{"ginecologia","DIU","contracepção","longa duração"}','','Pode ser usado como contracepção de emergência até 5 dias após'),
('gin-diu-levonorgestrel','DIU de Levonorgestrel','Levonorgestrel','Ginecologia','Contraceptivo','Dispositivo intrauterino','Intrauterino',false,false,false,'Inserção por profissional; duração 5 anos','','Spotting inicial, amenorreia (50% em 1 ano)','Perfuração uterina (rara)','Liberação local de progestágeno, atrofia endometrial','Contracepção, sangramento uterino anormal, endometriose','US controle pós-inserção','{"Mirena","Kyleena"}','{"ginecologia","DIU","progestágeno","endometriose"}','Vermelha',''),
('gin-clotrimazol-vaginal','Clotrimazol Vaginal','Clotrimazol','Ginecologia','Antifúngico','Creme vaginal','Vaginal',false,false,false,'1 aplicação intravaginal à noite por 7 dias (1%) ou dose única (500 mg)','','Irritação local, prurido','','Imidazol, inibição de síntese de ergosterol fúngico','Candidíase vulvovaginal','','{"Canesten","Gino-Canesten"}','{"ginecologia","candidíase","antifúngico"}','Sem tarja',''),
('gin-fluconazol-vaginal','Fluconazol VO para Candidíase','Fluconazol','Ginecologia','Antifúngico','Cápsula','VO',false,false,false,'150 mg dose única VO','','Náusea, cefaleia, dor abdominal','Hepatotoxicidade (rara)','Inibidor de 14-alfa-demetilase, bloqueia síntese de ergosterol','Candidíase vulvovaginal, candidíase recorrente','','{"Zoltec","Fluconol"}','{"ginecologia","candidíase","antifúngico sistêmico"}','Vermelha','Para recorrente: 150 mg/semana por 6 meses'),
('gin-metronidazol-vaginal','Metronidazol Gel Vaginal','Metronidazol','Ginecologia','Antibiótico','Gel vaginal','Vaginal',false,false,false,'1 aplicação intravaginal à noite por 5 dias','','Corrimento, irritação local','','Derivado nitroimidazólico, dano ao DNA de anaeróbios','Vaginose bacteriana','','{"Flagyl Vaginal","Colpistatin"}','{"ginecologia","vaginose","antibiótico"}','Vermelha',''),
('gin-misoprostol-obst','Misoprostol Obstétrico','Misoprostol','Ginecologia','Prostaglandina','Comprimido vaginal','Vaginal',false,false,false,'25 mcg vaginal a cada 6h (indução); 600-800 mcg SL (abortamento)','','Cólicas, diarreia, febre, calafrios','Rotura uterina (especialmente com cicatriz prévia)','Análogo de PGE1, amadurecimento cervical e contração uterina','Indução de parto, abortamento legal, hemorragia pós-parto','Dinâmica uterina, BCF','{"Cytotec","Prostokos"}','{"obstetrícia","indução","prostaglandina"}','Vermelha','Uso hospitalar exclusivo. Contraindicado em cicatriz uterina prévia para indução'),
('gin-progesterona-micronizada','Progesterona Micronizada','Progesterona','Ginecologia','Hormônio','Cápsula','VO',false,false,true,'200-400 mg/dia VO ou vaginal','','Sonolência, tontura, distensão abdominal','','Progesterona natural, ação no endométrio e manutenção da gestação','Suporte de fase lútea, ameaça de abortamento, TRH','','{"Utrogestan","Crinone"}','{"ginecologia","progesterona","gestação","TRH"}','Vermelha','Via vaginal tem melhor biodisponibilidade uterina'),
('gin-estradiol-valerato','Estradiol Valerato','Estradiol','Ginecologia','Hormônio','Comprimido','VO',false,false,false,'1-2 mg/dia','','Mastalgia, cefaleia, náusea','TEV, câncer de mama (uso prolongado)','Estrogênio natural, efeito trófico em tecidos estrogênio-dependentes','TRH na menopausa, hipoestrogenismo','Mamografia anual, perfil lipídico','{"Primogyna","Estrofem"}','{"ginecologia","menopausa","TRH","estrogênio"}','Vermelha',''),
('gin-tibolona','Tibolona','Tibolona','Ginecologia','Hormônio','Comprimido','VO',false,false,false,'2,5 mg 1x/dia','','Sangramento vaginal, ganho de peso','TEV, AVC (em > 60 anos)','Esteroide sintético com ação estrogênica, progestagênica e androgênica','TRH na menopausa, osteoporose pós-menopausa','Mamografia anual','{"Livial","Reduclim"}','{"ginecologia","menopausa","TRH"}','Vermelha','Iniciar apenas > 1 ano após menopausa'),
('gin-raloxifeno','Raloxifeno','Raloxifeno','Ginecologia','SERM','Comprimido','VO',false,false,false,'60 mg 1x/dia','','Fogachos, cãibras nas pernas','TEV','Modulador seletivo do receptor de estrogênio','Prevenção e tratamento de osteoporose pós-menopausa','DMO a cada 2 anos','{"Evista"}','{"ginecologia","osteoporose","SERM"}','Vermelha','Reduz risco de câncer de mama invasivo'),
('gin-clomifeno','Clomifeno','Clomifeno','Ginecologia','Indutor de ovulação','Comprimido','VO',false,false,false,'50-150 mg/dia por 5 dias (D3-D7 ou D5-D9)','150 mg/dia','Fogachos, distensão abdominal, alterações visuais','SHO (síndrome de hiperestimulação ovariana)','Antiestrogênio no hipotálamo, aumenta secreção de FSH','Indução de ovulação em anovulação, SOP','US folicular, estradiol sérico','{"Clomid","Indux"}','{"ginecologia","infertilidade","indução ovulação"}','Vermelha','Máximo 6 ciclos. Monitorar com US folicular'),
('gin-letrozol-fertil','Letrozol Fertilidade','Letrozol','Ginecologia','Inibidor de aromatase','Comprimido','VO',false,false,false,'2,5-7,5 mg/dia por 5 dias (D3-D7)','7,5 mg/dia','Cefaleia, fadiga, artralgias','SHO','Inibidor de aromatase, reduz estrogênio, aumenta FSH','Indução de ovulação (1ª linha em SOP), infertilidade','US folicular','{"Femara"}','{"ginecologia","infertilidade","SOP","aromatase"}','Vermelha','Primeira linha para indução de ovulação em SOP (ACOG)'),
('gin-cabergolina','Cabergolina','Cabergolina','Ginecologia','Agonista dopaminérgico','Comprimido','VO',false,false,false,'0,25-1 mg 2x/semana (hiperprolactinemia)','','Náusea, tontura, hipotensão ortostática','Fibrose valvar (doses altas crônicas)','Agonista D2 dopaminérgico, inibe secreção de prolactina','Hiperprolactinemia, inibição de lactação, prolactinoma','Prolactina sérica, ecocardiograma se uso > 2 anos','{"Dostinex"}','{"ginecologia","prolactinoma","dopaminérgico"}','Vermelha',''),
('gin-acido-tranexamico','Ácido Tranexâmico Ginecológico','Ácido tranexâmico','Ginecologia','Antifibrinolítico','Comprimido','VO',false,false,false,'250-500 mg 3x/dia durante menstruação','3 g/dia','Náusea, diarreia','TEV (raro)','Inibição competitiva da ativação do plasminogênio','Sangramento uterino anormal, menorragia','','{"Transamin","Hemoblock"}','{"ginecologia","menorragia","antifibrinolítico"}','Vermelha',''),
('gin-dienogeste','Dienogeste','Dienogeste','Ginecologia','Progestágeno','Comprimido','VO',false,false,false,'2 mg 1x/dia uso contínuo','','Sangramento irregular, cefaleia, mastalgia','','Progestágeno com forte ação antiproliferativa no endométrio','Endometriose','','{"Allurene","Visanne"}','{"ginecologia","endometriose","progestágeno"}','Vermelha','')
ON CONFLICT (id) DO UPDATE SET nome=EXCLUDED.nome, principio_ativo=EXCLUDED.principio_ativo, categoria=EXCLUDED.categoria, classe=EXCLUDED.classe, mecanismo_acao=EXCLUDED.mecanismo_acao, indicacoes=EXCLUDED.indicacoes, tarja=EXCLUDED.tarja, nomes_comerciais=EXCLUDED.nomes_comerciais, tags=EXCLUDED.tags;