INSERT INTO bulario_medications (id, nome, principio_ativo, categoria, classe, forma_farmaceutica, via, controlado, pediatria, gestacao_seguro, dose_pediatrica, dose_maxima, efeitos_adversos_comuns, efeitos_adversos_graves, mecanismo_acao, indicacoes, monitorizacao, nomes_comerciais, tags, tarja, dose_adulto, diluicao, tempo_infusao, observacoes) VALUES
-- NEONATOLOGIA (8 items)
('neo-surfactante-porcino','Surfactante Pulmonar Porcino','Alfaporactanto (Poractant alfa)','Neonatologia','Surfactante','Suspensão intratraqueal','Intratraqueal',false,true,false,'100-200 mg/kg dose inicial; pode repetir 100 mg/kg a cada 12h','','Bradicardia transitória, dessaturação','Hemorragia pulmonar, pneumotórax','Reduz tensão superficial alveolar, previne colapso alveolar','Síndrome do desconforto respiratório neonatal (SDR)','SpO2, FC contínua durante administração; RX tórax pós','{"Curosurf"}','{"neonatologia","SDR","surfactante","UTI neonatal"}','Vermelha','','Não diluir. Aquecer à temperatura corporal','',''),
('neo-cafeina-citrato','Cafeína Citrato','Citrato de cafeína','Neonatologia','Metilxantina','Ampola','IV',false,true,false,'Ataque: 20 mg/kg IV; Manutenção: 5-10 mg/kg/dia','','Taquicardia, irritabilidade, insônia','Convulsões, taquiarritmia','Antagonista de receptores de adenosina, estimulante do centro respiratório','Apneia da prematuridade','FC, nível sérico de cafeína se necessário (alvo 5-25 mcg/mL)','{"Peyona"}','{"neonatologia","apneia","prematuridade"}','Vermelha','','Pode ser administrado puro IV lento','30 minutos',''),
('neo-indometacina-iv','Indometacina IV Neonatal','Indometacina','Neonatologia','AINE','Ampola','IV',false,true,false,'0,1-0,25 mg/kg IV a cada 12-24h por 3 doses','','Oligúria transitória','IRA, enterocolite necrosante, perfuração intestinal','Inibidor de COX, promove fechamento do canal arterial','Persistência do canal arterial (PCA) em prematuros','Débito urinário, creatinina, plaquetas, ecocardiograma','{"Indocid IV"}','{"neonatologia","PCA","canal arterial"}','Vermelha','','Diluir em SF 0,9% sem conservante','20-30 minutos',''),
('neo-ibuprofeno-iv','Ibuprofeno IV Neonatal','Ibuprofeno lisina','Neonatologia','AINE','Ampola','IV',false,true,false,'10 mg/kg D1, depois 5 mg/kg D2 e D3','','Oligúria, hiperbilirrubinemia','IRA, hemorragia, NEC','Inibidor de COX, promove fechamento do canal arterial','PCA hemodinamicamente significativa em prematuros','Função renal, bilirrubina, plaquetas','{"Pedea"}','{"neonatologia","PCA","AINE"}','Vermelha','','Diluir em SF 0,9%','15 minutos',''),
('neo-fenobarbital','Fenobarbital Neonatal','Fenobarbital','Neonatologia','Anticonvulsivante','Ampola','IV',true,true,false,'Ataque: 20 mg/kg IV; Manutenção: 3-5 mg/kg/dia','40 mg/kg cumulativo','Sedação, hipotensão','Depressão respiratória, apneia','Potencializa ação do GABA no receptor GABA-A','Convulsões neonatais, primeira linha','Nível sérico (15-40 mcg/mL), FR, PA','{"Gardenal"}','{"neonatologia","convulsão","barbitúrico"}','Preta','','Diluir em SF 0,9%','15-20 minutos (máx 1 mg/kg/min)',''),
('neo-vitamina-k','Vitamina K1 (Fitomenadiona) Neonatal','Fitomenadiona','Neonatologia','Vitamina','Ampola','IM',false,true,false,'1 mg IM dose única ao nascimento (0,5 mg se < 1500g)','','Dor no local da injeção','Reação anafilactoide (rara, mais com IV)','Cofator para síntese de fatores de coagulação II, VII, IX, X','Profilaxia de doença hemorrágica do recém-nascido','','{"Kanakion"}','{"neonatologia","coagulação","profilaxia"}','Vermelha','','','',''),
('neo-aminofilina','Aminofilina Neonatal','Aminofilina','Neonatologia','Metilxantina','Ampola','IV',false,true,false,'Ataque: 6-8 mg/kg; Manutenção: 1,5-3 mg/kg/dose a cada 8-12h','','Taquicardia, agitação, vômitos','Arritmia, convulsões','Inibidor de fosfodiesterase e antagonista de adenosina','Apneia da prematuridade (alternativa à cafeína)','Nível sérico teofilina (7-12 mcg/mL), FC','{"Aminofilina"}','{"neonatologia","apneia","metilxantina"}','Vermelha','','Diluir em SG 5% ou SF 0,9%','20-30 minutos',''),
('neo-eritropoietina','Eritropoietina Neonatal','Eritropoietina alfa','Neonatologia','Fator de crescimento','Ampola','SC',false,true,false,'250-400 UI/kg/dose 3x/semana SC','','Dor no local, neutropenia leve','Hipertensão, trombose','Estimula eritropoiese na medula óssea','Anemia da prematuridade, redução de necessidade transfusional','Hemograma, reticulócitos, ferro sérico','{"Eprex","Eritromax"}','{"neonatologia","anemia","eritropoietina"}','Vermelha','','','',''),
-- OFTALMOLOGIA (14 items)
('oftalmo-tobramicina-col','Tobramicina Colírio','Tobramicina','Oftalmologia','Antibiótico','Colírio','Ocular',false,false,false,'','','Ardência, irritação local','','Aminoglicosídeo, inibição de síntese proteica bacteriana','Conjuntivite bacteriana, blefarite, úlcera de córnea','','{"Tobrex"}','{"oftalmologia","antibiótico","conjuntivite"}','Vermelha','1-2 gotas a cada 4-6h no olho afetado','','',''),
('oftalmo-ciprofloxacino-col','Ciprofloxacino Colírio','Ciprofloxacino','Oftalmologia','Antibiótico','Colírio','Ocular',false,false,false,'','','Ardência, precipitado corneano branco','','Fluoroquinolona, inibição de DNA girase e topoisomerase IV','Conjuntivite bacteriana, úlcera de córnea','','{"Ciloxan"}','{"oftalmologia","antibiótico","quinolona"}','Vermelha','1-2 gotas a cada 2h (úlcera) ou 4-6h (conjuntivite)','','',''),
('oftalmo-moxifloxacino-col','Moxifloxacino Colírio','Moxifloxacino','Oftalmologia','Antibiótico','Colírio','Ocular',false,false,false,'','','Irritação ocular leve','','Fluoroquinolona de 4ª geração, amplo espectro gram+/gram-','Profilaxia pós-operatória, conjuntivite bacteriana','','{"Vigamox"}','{"oftalmologia","antibiótico","pós-operatório"}','Vermelha','1 gota 3x/dia por 7 dias','','',''),
('oftalmo-prednisolona-col','Prednisolona Acetato Colírio','Prednisolona acetato','Oftalmologia','Corticosteroide','Colírio','Ocular',false,false,false,'','','Aumento de PIO, catarata','Glaucoma corticosteroidogênico, perfuração corneana','Anti-inflamatório esteroidal, inibição de fosfolipase A2','Uveíte anterior, pós-operatório ocular, ceratite não infecciosa','PIO a cada consulta','{"Pred Fort"}','{"oftalmologia","corticoide","uveíte"}','Vermelha','1-2 gotas a cada 1-6h conforme gravidade, com desmame progressivo','','',''),
('oftalmo-tropicamida','Tropicamida Colírio','Tropicamida','Oftalmologia','Midriático','Colírio','Ocular',false,false,false,'','','Fotofobia, visão turva temporária','Glaucoma de ângulo fechado (raro)','Anticolinérgico, bloqueio muscarínico no esfíncter pupilar','Midríase para exame de fundo de olho, cicloplegia diagnóstica','','{"Mydriacyl"}','{"oftalmologia","midriático","exame"}','Vermelha','1-2 gotas, pode repetir após 5 min; efeito dura 4-6h','','',''),
('oftalmo-fenilefrina-col','Fenilefrina Colírio 10%','Fenilefrina','Oftalmologia','Midriático','Colírio','Ocular',false,false,false,'','','Ardência transitória','Hipertensão arterial (absorção sistêmica)','Agonista alfa-1 adrenérgico, contração do músculo dilatador da pupila','Midríase para fundoscopia, associação com tropicamida','','{"Fenilefrina Colírio"}','{"oftalmologia","midriático"}','Vermelha','1 gota, pode repetir após 5-10 min','','',''),
('oftalmo-dorzolamida-timolol','Dorzolamida + Timolol Colírio','Dorzolamida + Timolol','Oftalmologia','Antiglaucomatoso','Colírio','Ocular',false,false,false,'','','Ardência, gosto amargo','Broncoespasmo, bradicardia (timolol)','Inibidor de anidrase carbônica + betabloqueador; redução dupla de produção de humor aquoso','Glaucoma de ângulo aberto, hipertensão ocular','PIO regular','{"Cosopt"}','{"oftalmologia","glaucoma","combinação"}','Vermelha','1 gota 2x/dia','','',''),
('oftalmo-latanoprosta','Latanoprosta Colírio','Latanoprosta','Oftalmologia','Antiglaucomatoso','Colírio','Ocular',false,false,false,'','','Hiperemia conjuntival, escurecimento da íris, crescimento de cílios','Edema macular cistoide','Análogo de prostaglandina F2alfa, aumenta drenagem uveoescleral','Glaucoma de ângulo aberto, hipertensão ocular — primeira linha','PIO, cor da íris','{"Xalatan"}','{"oftalmologia","glaucoma","prostaglandina"}','Vermelha','1 gota à noite no olho afetado','','',''),
('oftalmo-brimonidina','Brimonidina Colírio','Brimonidina','Oftalmologia','Antiglaucomatoso','Colírio','Ocular',false,false,false,'','','Ardência, boca seca, fadiga','Sonolência excessiva (especialmente crianças — contraindicado < 2 anos)','Agonista alfa-2 adrenérgico, reduz produção e aumenta drenagem de humor aquoso','Glaucoma, hipertensão ocular, adjuvante pós-laser','','{"Alphagan"}','{"oftalmologia","glaucoma","alfa-agonista"}','Vermelha','1 gota 2-3x/dia','','',''),
('oftalmo-travoprosta','Travoprosta Colírio','Travoprosta','Oftalmologia','Antiglaucomatoso','Colírio','Ocular',false,false,false,'','','Hiperemia conjuntival, mudança cor da íris','','Análogo de prostaglandina, aumenta drenagem uveoescleral','Glaucoma de ângulo aberto','','{"Travatan"}','{"oftalmologia","glaucoma","prostaglandina"}','Vermelha','1 gota à noite','','',''),
('oftalmo-brinzolamida','Brinzolamida Colírio','Brinzolamida','Oftalmologia','Antiglaucomatoso','Colírio','Ocular',false,false,false,'','','Visão turva transitória, gosto amargo','','Inibidor de anidrase carbônica tópico, reduz produção de humor aquoso','Glaucoma de ângulo aberto, adjuvante','','{"Azopt"}','{"oftalmologia","glaucoma"}','Vermelha','1 gota 2-3x/dia','','',''),
('oftalmo-pilocarpina','Pilocarpina Colírio','Pilocarpina','Oftalmologia','Miótico','Colírio','Ocular',false,false,false,'','','Miose, cefaleia frontal, visão turva','Descolamento de retina (raro)','Agonista colinérgico muscarínico, contração do esfíncter pupilar e músculo ciliar','Glaucoma de ângulo fechado agudo (emergência), teste provocativo','','{"Pilocarpina"}','{"oftalmologia","glaucoma","miótico","emergência"}','Vermelha','1-2 gotas a cada 5-15 min na crise; manutenção 3-4x/dia','','',''),
('oftalmo-olopatadina','Olopatadina Colírio','Olopatadina','Oftalmologia','Anti-alérgico','Colírio','Ocular',false,false,false,'','','Ardência leve','','Anti-histamínico H1 e estabilizador de mastócitos','Conjuntivite alérgica','','{"Patanol","Lastacaft"}','{"oftalmologia","alergia","conjuntivite"}','Vermelha','1 gota 2x/dia (0,1%) ou 1 gota 1x/dia (0,2%)','','',''),
('oftalmo-cetorolaco-col','Cetorolaco Colírio','Cetorolaco trometamol','Oftalmologia','AINE','Colírio','Ocular',false,false,false,'','','Ardência, irritação','','Inibidor de COX, anti-inflamatório não esteroidal tópico','Inflamação pós-operatória ocular, prurido alérgico sazonal','','{"Acular"}','{"oftalmologia","AINE","pós-operatório"}','Vermelha','1 gota 4x/dia por 2 semanas pós-cirurgia','','','')
ON CONFLICT (id) DO UPDATE SET nome=EXCLUDED.nome, principio_ativo=EXCLUDED.principio_ativo, categoria=EXCLUDED.categoria, classe=EXCLUDED.classe, mecanismo_acao=EXCLUDED.mecanismo_acao, indicacoes=EXCLUDED.indicacoes, efeitos_adversos_comuns=EXCLUDED.efeitos_adversos_comuns, efeitos_adversos_graves=EXCLUDED.efeitos_adversos_graves, tarja=EXCLUDED.tarja, nomes_comerciais=EXCLUDED.nomes_comerciais, tags=EXCLUDED.tags;